#!/usr/sbin/nft -f
# Own only this table; retain Tailscale's tables.
table inet den_filter
flush table inet den_filter
table inet den_filter {
  chain input {
    type filter hook input priority 10; policy drop;
    ct state established,related accept
    iifname "lo" accept
    iifname "tailscale0" accept
    ct state invalid drop
    ip protocol icmp accept
    ip6 nexthdr ipv6-icmp accept
    udp sport 67 udp dport 68 accept
    tcp dport { 22, 80, 443, 5349, 7881 } accept
    udp dport 3478 accept
    udp dport 50000-50200 accept
  }
}
