import type { components } from './schema'
type S = components['schemas']
export type User = S['User']
export type Channel = S['Channel']
export type Category = S['Category']
export type Message = S['Message']
export type Upload = S['Upload']
export type Session = S['Session']
export type Event = S['Event']
export type ApiError = S['ApiError']
export type Invite = S['Invite']
export type Token = S['Token']
export type TokenSecret = S['TokenSecret']
export type BotCreated = S['BotCreated']
